# Generated by Django 5.2.11 on 2026-02-17 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("consultations", "0002_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VisualInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("malaria", "Mikroskopi Malaria"),
                            ("leprosy", "Dermatologi Kusta"),
                            ("fungal", "Dermatologi Jamur"),
                            ("chest_xray", "Radiologi Dada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="inspections/%Y/%m/")),
                ("image_gcs_path", models.CharField(blank=True, max_length=500)),
                ("findings", models.TextField(blank=True)),
                ("model_used", models.CharField(default="medgemma-4b", max_length=50)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections",
                        to="consultations.consultationsession",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "visual_inspection",
                "ordering": ["-created_at"],
            },
        ),
    ]
