# Generated by Django 5.2.11 on 2026-02-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("laboratory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visualinspection",
            name="inspection_type",
            field=models.CharField(
                choices=[
                    ("chest_xray", "Rontgen Dada (Chest X-Ray)"),
                    ("knee_xray", "Rontgen Lutut (Knee X-Ray)"),
                    ("ct_scan", "CT Scan"),
                    ("dermatology", "Dermatologi (Kulit)"),
                    ("ophthalmology", "Oftalmologi (Mata/Fundus)"),
                    ("histopathology", "Histopatologi"),
                    ("lab_report", "Laporan Lab Klinis"),
                ],
                max_length=20,
            ),
        ),
    ]
