# Generated by Django 5.2.11 on 2026-02-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CeleryTaskTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "celery_task_tracker",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("ai_4b", "MedGemma 4B"),
                            ("ai_27b", "MedGemma 27B"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("model_used", models.CharField(blank=True, max_length=50)),
                ("escalated", models.BooleanField(default=False)),
                (
                    "triage_level",
                    models.CharField(
                        choices=[
                            ("green", "Hijau (Ringan)"),
                            ("yellow", "Kuning (Perhatian)"),
                            ("red", "Merah (Darurat)"),
                            ("none", "Tidak Ada"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                ("rag_sources", models.JSONField(blank=True, default=list)),
                ("suggested_actions", models.JSONField(blank=True, default=list)),
                ("extracted_data", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "chat_message",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("patient", "Konsultasi Pasien"),
                            ("staff", "Konsultasi Staf"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "title",
                    models.CharField(blank=True, default="Sesi Baru", max_length=200),
                ),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "consultation_session",
                "ordering": ["-created_at"],
            },
        ),
    ]
