# Generated by Django 5.2.11 on 2026-02-17 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("consultations", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VillageReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("content", models.TextField()),
                ("executive_summary", models.TextField(blank=True)),
                ("disease_analysis", models.TextField(blank=True)),
                ("logistics_needs", models.TextField(blank=True)),
                ("trend_projection", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("impact_estimate", models.TextField(blank=True)),
                ("total_consultations", models.IntegerField(default=0)),
                ("total_inspections", models.IntegerField(default=0)),
                ("total_patients_served", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "village_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiseaseReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.CharField(max_length=300)),
                ("category", models.CharField(db_index=True, max_length=100)),
                ("medications", models.TextField(blank=True)),
                ("supplies_needed", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("ringan", "Ringan"),
                            ("sedang", "Sedang"),
                            ("berat", "Berat"),
                        ],
                        default="ringan",
                        max_length=10,
                    ),
                ),
                ("follow_up_days", models.IntegerField(default=7)),
                ("clinical_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="consultations.consultationsession",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disease_reports",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "disease_report",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "-created_at"],
                        name="disease_rep_categor_e79270_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="disease_rep_created_47271f_idx"
                    ),
                ],
            },
        ),
    ]
