# Generated by Django 5.2.11 on 2026-02-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EducationMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disease_name", models.CharField(max_length=200)),
                ("disease_category", models.CharField(db_index=True, max_length=100)),
                ("case_count", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("symptoms", models.TextField(blank=True)),
                ("prevention", models.TextField(blank=True)),
                ("when_to_visit", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "education_material",
                "ordering": ["-case_count"],
            },
        ),
    ]
