# Generated by Django 5.2.11 on 2026-02-17 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CropRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("scientific_name", models.CharField(blank=True, max_length=200)),
                ("emoji", models.CharField(default="🌱", max_length=10)),
                ("nutritional_benefits", models.TextField()),
                ("stunting_relevance", models.TextField(blank=True)),
                ("planting_guide", models.TextField()),
                ("harvest_time", models.CharField(blank=True, max_length=100)),
                ("compatible_climates", models.JSONField(default=list)),
                ("compatible_soils", models.JSONField(default=list)),
            ],
            options={
                "db_table": "crop_recommendation",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NutritionChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "nutrition_chat_session",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NutritionChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[("user", "User"), ("ai", "AI Nutrisi")], max_length=5
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="nutrition.nutritionchatsession",
                    ),
                ),
            ],
            options={
                "db_table": "nutrition_chat_message",
                "ordering": ["timestamp"],
            },
        ),
    ]
