# Generated by Django 5.2.11 on 2026-02-17 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "nik",
                    models.CharField(
                        blank=True, db_index=True, max_length=16, verbose_name="NIK"
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("L", "Laki-laki"), ("P", "Perempuan")], max_length=1
                    ),
                ),
                ("village", models.CharField(blank=True, max_length=200)),
                ("address", models.TextField(blank=True)),
                (
                    "weight",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Berat Badan (kg)"
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Tinggi Badan (cm)"
                    ),
                ),
                (
                    "blood_pressure_sys",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tekanan Darah Sistolik"
                    ),
                ),
                (
                    "blood_pressure_dia",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tekanan Darah Diastolik"
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(blank=True, null=True, verbose_name="Suhu (°C)"),
                ),
                (
                    "heart_rate",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Heart Rate (bpm)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("stabil", "Stabil"),
                            ("monitoring", "Monitoring"),
                            ("kritis", "Kritis"),
                        ],
                        default="stabil",
                        max_length=15,
                    ),
                ),
                (
                    "stunting_status",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("stunting", "Stunting"),
                            ("severe_stunting", "Stunting Berat"),
                            ("na", "Tidak Berlaku"),
                        ],
                        default="na",
                        max_length=20,
                    ),
                ),
                ("z_score", models.FloatField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="patient_photos/%Y/%m/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "patient",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["full_name"], name="patient_full_na_21fbbe_idx"
                    ),
                    models.Index(fields=["village"], name="patient_village_52dbfc_idx"),
                    models.Index(fields=["status"], name="patient_status_774423_idx"),
                ],
            },
        ),
    ]
